### ISSUE TITLE
可以支持微信小程序使用么

### ISSUE THREAD

**Issue by jiangjj1993** [zhipeng-jia/snappyjs#4]

**Comment by zhipeng-jia** [comment]
我没测试过微信小程序的环境下是否能使用 snappyjs。
理论上来说只要微信小程序的 JavaScript 引擎支持 ArrayBuffer，snappyjs 就应该能正常工作。
如果你有条件是否能帮助测试一下？

**Comment by jiangjj1993** [comment]
@zhipeng-jia  恩，不行，
WAService.js:15 Uncaught TypeError: Cannot read property 'SnappyJS' of undefined
    at Object.1../index (snappyjs.min.js? [sm]:13)
