### ISSUE TITLE
Error: Invalid Snappy bitstream

### ISSUE THREAD

**Issue by s0kil** [zhipeng-jia/snappyjs#6]
I'm getting this error when trying to decompress:

Here is the code:
```JavaScript
const SnappyJS = require('snappyjs');


// decompress(ArrayBuffer || Buffer || Uint8Array) -> (compressed byte stream)
function decompress(compressedData) {
  return SnappyJS.uncompress(compressedData);
}



(async () => {
  let cssData = await fetch("normalize.css.snappy")
    .then(r => r.arrayBuffer())
    .then(data => decompress(data));

  console.log(cssData);
})()
```

**Comment by zhipeng-jia** [comment]
What's the error message?

**Comment by DanielSokil** [comment]
```JavaScript
23:34:22.210 index.js:77 Uncaught (in promise) Error: Invalid Snappy bitstream
    at Object.uncompress [as snappy] (index.js:77)
    at decompress (index.js:11)
    at fetch.then.then.data (index.js:19)
```

I compressed the file using a python module:
`python3 -m snappy -c normalize.css normalize.css.snappy`

**Comment by alietors** [comment]
s0k

> ```js
> 23:34:22.210 index.js:77 Uncaught (in promise) Error: Invalid Snappy bitstream
>     at Object.uncompress [as snappy] (index.js:77)
>     at decompress (index.js:11)
>     at fetch.then.then.data (index.js:19)
> ```
> 
> It's coming from here:
> 
> ```js
>     if (!decompressor.uncompressToBuffer(uncompressed)) {
>       throw new Error('Invalid Snappy bitstream')
>     }
> ```
> 
> I compressed the file using a python module:
> `python3 -m snappy -c normalize.css normalize.css.snappy`

Did you found the problem? We are seeing this issue

**Comment by zhipeng-jia** [comment]
@alietors Could you attach the uncompressed file?

**Comment by alietors** [comment]
I don't have the uncompressed file. I think the problem is the file was
generated with python and it includes timestamps that are in microseconds,
causing problems on js.

**Comment by zhipeng-jia** [comment]
I feel the problem is snappyjs does not implement snappy framing format:

https://github.com/andrix/python-snappy/blob/83ba7047e0d1f67b38f0d5c8f43ca131bae46a29/src/snappy/snappy.py#L183

I'll see if I could fix it.

I found another package [snappy-stream](https://github.com/kesla/node-snappy-stream) provides framing support.

**Comment by kallangerard** [comment]
Was this issue fixed?
